// Production-compiled WASM; synthetic same-origin reporting only, no real finance IO.
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.KC_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(process.env.KC_WEB_ROOT||'target/dx/web/release/web/public');
const output=path.resolve(process.env.KC_BROWSER_OUTPUT||'tenant-finance-browser-results');await fs.mkdir(output,{recursive:true});
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',U='33333333-3333-4333-8333-333333333333',V='44444444-4444-4444-8444-444444444444',O='55555555-5555-4555-8555-555555555555';
const stamp='2026-09-24T00:00:00Z';
const server=http.createServer(async(req,res)=>{try{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(file!==root&&!file.startsWith(root+path.sep))throw Error('invalid asset');let data;try{data=await fs.readFile(file);}catch{file=path.join(root,'index.html');data=await fs.readFile(file);}const mime={'.html':'text/html','.js':'text/javascript','.wasm':'application/wasm','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);}catch{res.writeHead(500);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let currentPage;const errors=[],cases=[];
const usage=n=>({id:`aaaaaaaa-aaaa-4aaa-8aaa-${String(n).padStart(12,'0')}`,request_id:O,tenant_id:A,user_id:n%2?V:U,produce_ai_key_id:O,model_name:`model-${n}`,provider_name:'openai',account_id:O,input_tokens:1,output_tokens:2,total_tokens:3,input_unit_price_snapshot:'1E-10',output_unit_price_snapshot:'0.0000000001',user_amount:'9999999999.9999999999',currency:n%2?'CNY':'USD',usage_source:'gateway_accumulated',status:'success',started_at:stamp,finished_at:stamp,created_at:stamp});
const order=()=>({id:O,tenant_id:A,user_id:V,amount:'7.0000000001',currency:'CNY',status:'pending',payment_method:'wechatpay',payment_scene:'native',paid_at:null,closed_at:null,expired_at:'2030-01-01T00:00:00Z',created_at:stamp,updated_at:stamp,pay_url:'https://private.invalid/never-display',subject:'never-display-subject',notify_data:{secret:'never-display-callback'}});
async function fixture({selected=A,role='none',admin=true}={}){
 const state={selected,role,admin,calls:[],unknown:[],foreign:false,fail:false,hold:false,release:null,rows:Array.from({length:21},(_,i)=>usage(i+1)),orders:[order()]};
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>{localStorage.setItem('keyc_access_token','fixture-token');localStorage.setItem('keyc_lang','en');});
 const page=await context.newPage();page.setDefaultTimeout(20000);currentPage=page;page.on('pageerror',e=>errors.push(e.message));
 const profile=()=>({id:U,user_id:U,email:'report@fixture.invalid',name:'Finance reviewer',platform_role:state.role,status:'active',created_at:stamp,selected_tenant:state.selected?{id:state.selected,name:state.selected===A?'Tenant A':'Tenant B',slug:'fixture',tenant_role:state.selected===A&&state.admin?'admin':'member',authz_version:1,membership_authz_version:1}:null,memberships:[{tenant_id:A,tenant_name:'Tenant A',tenant_role:state.admin?'admin':'member',status:'active',authz_version:1},{tenant_id:B,tenant_name:'Tenant B',tenant_role:'member',status:'active',authz_version:1}],capabilities:{platform:state.role==='root'?['users:manage']:state.role==='operator'?['platform:tenant_health']:[],tenant:state.selected===A&&state.admin?['tenant:manage']:[]}});
 await page.route('**/*',async route=>{
  const request=route.request(),url=new URL(request.url());if(url.origin!==base)return route.abort();if(!url.pathname.startsWith('/api/'))return route.continue();const p=url.pathname,m=request.method(),body=request.postDataJSON();state.calls.push({path:p,method:m,query:url.search,body});
  const answer=(v,status=200)=>route.fulfill({status,contentType:'application/json',headers:{'Cache-Control':'private, no-store'},body:JSON.stringify(v).replaceAll('"EXACT_INTEGER_FIXTURE"','9007199254740993')});
  const paginate=rows=>{const n=Number(url.searchParams.get('page')||1),size=Number(url.searchParams.get('page_size')||20);return {items:rows.slice((n-1)*size,n*size),total:rows.length,page:n,page_size:size,total_pages:Math.ceil(rows.length/size)};};
  if(p==='/api/v1/settings/public')return answer({site_name:'KeyCompute',distribution_enabled:false});
  if(p==='/api/v1/me'&&m==='GET')return answer(profile());
  if(p==='/api/v1/me/tenant'){state.selected=body.tenant_id;return answer({...profile(),access_token:'fixture-selected',token_type:'Bearer',expires_in:3600});}
  if(p===`/api/v1/tenants/${state.selected}`)return answer({id:state.selected,owner_user_id:U,name:state.selected===A?'Tenant A':'Tenant B',slug:'fixture',description:null,status:'active',default_rpm_limit:60,default_tpm_limit:100000,authz_version:1,tenant_role:state.selected===A?'admin':'member',membership_authz_version:1});
  const prefix=`/api/v1/tenants/${A}`;
  if(p.startsWith(prefix+'/')){
   assert.equal(m,'GET','reporting UI must never send financial mutations');assert.equal(url.searchParams.has('tenant_id'),false);
   if(state.fail)return answer({error:{message:'report storage unavailable'}},503);
   const owner=url.searchParams.get('owner_user_id');
   if(p===prefix+'/billing/records'){let rows=state.rows.filter(r=>!owner||r.user_id===owner);if(state.foreign)rows=rows.map(r=>({...r,tenant_id:B}));return answer(paginate(rows));}
   if(p===prefix+'/billing/stats'){const rows=state.rows.filter(r=>!owner||r.user_id===owner);const currencies=[...new Set(rows.map(r=>r.currency))].map(currency=>({currency,total_requests:'EXACT_INTEGER_FIXTURE',total_input_tokens:1,total_output_tokens:2,total_tokens:3,total_amount:'9999999999.9999999999'}));return answer({from:url.searchParams.get('from'),to:url.searchParams.get('to'),currencies});}
   if(p.startsWith(prefix+'/billing/records/')){if(state.hold)await new Promise(resolve=>state.release=resolve);const row=state.rows.find(r=>r.id===p.split('/').at(-1));return answer(row?{...row,...(state.foreign?{user_id:U}: {})}:{error:{message:'not found'}},row?200:404);}
   if(p===prefix+'/payments/orders'){const status=url.searchParams.get('status');return answer(paginate(state.orders.filter(r=>(!owner||r.user_id===owner)&&(!status||r.status===status))));}
   if(p===prefix+`/payments/orders/${O}`)return answer(state.orders[0]);
   if(p.startsWith(prefix+'/balances/')){const u=p.split('/').at(-1);if(![U,V].includes(u))return answer({error:{message:'wallet owner not found'}},404);return answer({tenant_id:A,user_id:u,available_balance:'0',frozen_balance:'0',total_recharged:'0',total_consumed:'0',initialized:false,as_of:stamp});}
  }
  state.unknown.push(`${m} ${p}`);return answer({error:{message:'unexpected fixture route'}},404);
 });
 return {state,page,context};
}
const rows=page=>page.locator('.tenant-finance tbody tr');
async function showDetail(page){await rows(page).first().getByRole('button',{name:'Inspect financial metadata',exact:true}).click();const d=page.getByRole('dialog');await d.locator('pre').waitFor();return d;}
try{
 let {state,page,context}=await fixture();await page.goto(base+'/tenant/finance');await rows(page).first().waitFor();await page.locator('.finance-currency-totals').getByText('CNY',{exact:true}).waitFor();await page.locator('.finance-currency-totals').getByText('USD',{exact:true}).waitFor();assert.match(await page.locator('.finance-currency-totals').innerText(),/9007199254740993/);assert.match(await rows(page).first().innerText(),/9999999999\.9999999999/);
 const statsCalls=state.calls.filter(c=>c.path.endsWith('/billing/stats')).length;await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByText('model-21',{exact:true}).waitFor();assert.equal(state.calls.filter(c=>c.path.endsWith('/billing/stats')).length,statsCalls,'pagination must not refetch expensive totals');
 let d=await showDetail(page);assert.match(await d.locator('pre').innerText(),/1E-10|0\.0000000001/);await d.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('#finance-owner').fill('bad&tenant_id='+B);const before=state.calls.length;await page.getByRole('button',{name:'Apply report filters',exact:true}).click();await page.locator('.tenant-finance > [role="alert"]').waitFor();assert.equal(state.calls.length,before);
 await page.locator('#finance-owner').fill(V);await page.getByRole('button',{name:'Apply report filters',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.tenant-finance tbody')?.querySelectorAll('tr').length===11);assert.equal(await rows(page).count(),11);
 const filtered=state.calls.filter(c=>c.path.endsWith('/billing/records')).at(-1);assert.equal(new URLSearchParams(filtered.query).get('owner_user_id'),V);
 await page.locator('#finance-from').fill('2026-01-01T00:00:00Z');await page.locator('#finance-to').fill('2026-03-01T00:00:00Z');const invalidBefore=state.calls.length;await page.getByRole('button',{name:'Apply report filters',exact:true}).click();await page.locator('.tenant-finance > [role="alert"]').waitFor();assert.equal(state.calls.length,invalidBefore);
 await page.getByRole('button',{name:'Payment records',exact:true}).click();await rows(page).first().waitFor();assert.match(await rows(page).first().innerText(),/7\.0000000001/);d=await showDetail(page);assert.doesNotMatch(await d.innerText(),/never-display|pay_url|notify_data|subject/);await d.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('#finance-payment-state').selectOption('paid');await page.getByRole('button',{name:'Apply report filters',exact:true}).click();await page.getByText('No records',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Member wallet',exact:true}).click();await page.locator('.tenant-member-wallet').waitFor();assert.match(await page.locator('.tenant-member-wallet').innerText(),/no wallet has been initialized/);const walletRequests=state.calls.filter(c=>c.path.includes('/balances/'));assert.equal(walletRequests.length,1);assert.equal(walletRequests[0].path,`/api/v1/tenants/${A}/balances/${V}`);
 await page.locator('#finance-owner').fill('');await page.getByRole('button',{name:'Apply report filters',exact:true}).click();await page.getByText('Select and apply a member UUID to read that member\'s wallet.',{exact:true}).waitFor();assert.equal(state.calls.filter(c=>c.path.includes('/balances/')).length,1);
 await page.screenshot({path:path.join(output,'tenant-finance.png'),fullPage:true});assert.deepEqual(state.unknown,[]);assert.equal(state.calls.filter(c=>c.method!=='GET').length,0);cases.push('exact decimals and large counters, independent currency totals, page memoization, safe metadata and read-only uninitialized wallet');await context.close();
 ({state,page,context}=await fixture());state.hold=true;await page.goto(base+'/tenant/finance');await rows(page).first().waitFor();await rows(page).first().getByRole('button',{name:'Inspect financial metadata',exact:true}).click();for(let i=0;i<200&&!state.release;i++)await page.waitForTimeout(10);assert.ok(state.release);
 await page.evaluate(()=>{history.pushState(null,'','/tenant');window.dispatchEvent(new PopStateEvent('popstate'));});await page.locator('#workspace-select').waitFor();await page.locator('#workspace-select').selectOption(B);await page.getByRole('button',{name:'Switch workspace',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#tenant-name')?.value==='Tenant B');state.release();await page.waitForTimeout(150);assert.equal(await page.locator('.finance-inspector').count(),0);assert.doesNotMatch(await page.locator('body').innerText(),/9999999999\.9999999999|model-1/);assert.deepEqual(state.unknown,[]);cases.push('late private detail cannot publish into another member workspace');await context.close();
 for(const config of [{selected:null,role:'root'},{selected:null,role:'operator'},{admin:false}]){({state,page,context}=await fixture(config));await page.goto(base+'/tenant/finance');await page.getByText('Current tenant administrator capability is required.',{exact:true}).waitFor();assert.equal(state.calls.filter(c=>c.path.includes('/billing/')||c.path.includes('/payments/')||c.path.includes('/balances/')).length,0);await context.close();}
 ({state,page,context}=await fixture());state.foreign=true;await page.goto(base+'/tenant/finance');await page.locator('.tenant-finance > [role="alert"]').waitFor();assert.equal(await rows(page).count(),0);await context.close();
 ({state,page,context}=await fixture());await page.goto(base+'/tenant/finance');await rows(page).first().waitFor();await page.setViewportSize({width:390,height:844});d=await showDetail(page);const box=await d.boundingBox();assert.ok(box&&box.x>=0&&box.x+box.width<=391);assert.equal(await d.evaluate(el=>el.contains(document.activeElement)),true);await page.screenshot({path:path.join(output,'finance-detail-mobile.png'),fullPage:true});await page.keyboard.press('Escape');await d.waitFor({state:'detached'});assert.deepEqual(state.unknown,[]);cases.push('membership gates, foreign report rejection and bounded private metadata dialog');await context.close();
 assert.deepEqual(errors,[]);const report={passed:true,basis:'production-compiled WASM with synthetic HTTP, not production finance or backend-authority validation',cases,page_errors:errors};await fs.writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){if(currentPage&&!currentPage.isClosed()){console.error((await currentPage.locator('body').innerText()).slice(0,9000));await currentPage.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});}console.error(error);process.exitCode=1;}
finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
