// Production-compiled WASM with synthetic same-origin provider HTTP only.
import http from 'node:http'; import fs from 'node:fs/promises'; import path from 'node:path'; import assert from 'node:assert/strict';
const {chromium}=await import(process.env.KC_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(process.env.KC_WEB_ROOT||'target/dx/web/release/web/public'),out=path.resolve(process.env.KC_BROWSER_OUTPUT||'tenant-provider-browser-results');await fs.mkdir(out,{recursive:true});
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',U='33333333-3333-4333-8333-333333333333',ACC='44444444-4444-4444-8444-444444444444',BIND='55555555-5555-4555-8555-555555555555',stamp='2026-09-26T00:00:00Z';
const server=http.createServer(async(req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://x').pathname));try{let d=await fs.readFile(f);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.wasm':'application/wasm','.css':'text/css','.woff2':'font/woff2'}[path.extname(f)]||'application/octet-stream'});res.end(d)}catch{let d=await fs.readFile(path.join(root,'index.html'));res.writeHead(200,{'Content-Type':'text/html'});res.end(d)}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const errors=[],cases=[];
async function fixture({admin=true,selected=A}={}){const state={admin,selected,calls:[],unknown:[],hold:false,release:null,account:{id:ACC,tenant_id:A,tenant_active:true,name:'Account A',provider:'openai',api_key_preview:'sk-***',api_base:'https://example.invalid/v1',models:['m'],api_capabilities:['responses'],rpm_limit:60,tpm_limit:100000,current_rpm:0,is_active:true,is_healthy:true,health_status:'healthy',health_penalty:0,health_reason:null,routing_eligible:true,pool_enabled:false,passthrough_binding_count:1,last_probe_at:null,last_probe_status:null,last_probe_error_code:null,priority:0,visibility:'tenant',created_at:stamp,last_used_at:null},binding:{id:BIND,account_id:ACC,account_name:'Account A',tenant_id:A,tenant_name:'Tenant A',provider:'openai',is_global:false,pool_enabled:false,revision:1,models_supported:['m'],health_status:'healthy',health_reason_code:null,created_at:stamp,updated_at:stamp}};const c=await browser.newContext({viewport:{width:1280,height:900}});await c.addInitScript(()=>{localStorage.setItem('keyc_access_token','fixture-token');localStorage.setItem('keyc_lang','en')});const page=await c.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);
const profile=()=>({id:U,user_id:U,email:'p@fixture.invalid',name:'P',platform_role:'none',status:'active',created_at:stamp,selected_tenant:state.selected?{id:state.selected,name:state.selected===A?'Tenant A':'Tenant B',slug:'x',tenant_role:state.admin&&state.selected===A?'admin':'member',authz_version:1,membership_authz_version:1}:null,memberships:[{tenant_id:A,tenant_name:'Tenant A',tenant_role:state.admin?'admin':'member',status:'active',authz_version:1},{tenant_id:B,tenant_name:'Tenant B',tenant_role:'member',status:'active',authz_version:1}],capabilities:{platform:[],tenant:state.admin&&state.selected===A?['tenant:manage']:[]}});
await page.route('**/*',async route=>{const r=route.request(),url=new URL(r.url());if(url.origin!==base)return route.abort();if(!url.pathname.startsWith('/api/'))return route.continue();const p=url.pathname,m=r.method(),body=r.postDataJSON();state.calls.push({path:p,method:m,query:url.search,body});const ans=(v,status=200)=>route.fulfill({status,contentType:'application/json',headers:{'Cache-Control':'private, no-store'},body:JSON.stringify(v)});
if(p==='/api/v1/settings/public')return ans({site_name:'KeyCompute',distribution_enabled:false});if(p==='/api/v1/me'&&m==='GET')return ans(profile());if(p==='/api/v1/me/tenant'){state.selected=body.tenant_id;return ans({...profile(),access_token:'next',token_type:'Bearer',expires_in:3600})}if(p===`/api/v1/tenants/${state.selected}`)return ans({id:state.selected,owner_user_id:U,name:'Tenant',slug:'x',description:null,status:'active',default_rpm_limit:60,default_tpm_limit:100000,authz_version:1,tenant_role:state.admin?'admin':'member',membership_authz_version:1});
const pre=`/api/v1/tenants/${A}`;if(p.startsWith(pre)){assert.equal(url.searchParams.has('tenant_id'),false);assert.equal(body?.tenant_id,undefined);assert.equal(body?.is_global,undefined);if(state.hold)await new Promise(x=>state.release=x);
if(p===pre+'/accounts'&&m==='GET')return ans({accounts:[state.account],total:1,page:1,page_size:20,total_pages:1});if(p===pre+'/accounts'&&m==='POST'){state.account={...state.account,name:body.name,models:body.models,api_capabilities:body.api_capabilities,pool_enabled:body.pool_enabled,passthrough_binding_count:0};return ans(state.account)}if(p===pre+'/accounts/'+ACC&&m==='PUT'){state.account={...state.account,...body};return ans(state.account)}if(p===pre+'/accounts/'+ACC+'/test')return ans({status:'ok'});if(p===pre+'/accounts/'+ACC+'/refresh')return ans({models:['m']});
if(p===pre+'/passthrough-bindings'&&m==='GET')return ans({bindings:[state.binding],total:1,page:1,page_size:20,total_pages:1});if(p===pre+'/passthrough-bindings/options')return ans({accounts:[{id:ACC,name:'Account A',provider:'openai',pool_enabled:false,models:['m']}],total:1,page:1,page_size:100,total_pages:1});if(p===pre+'/passthrough-bindings/'+BIND&&m==='PUT'){assert.equal(body.expected_revision,1);state.binding={...state.binding,pool_enabled:body.pool_enabled,revision:2};return ans(state.binding)}if(p===pre+'/passthrough-bindings/'+BIND+'/probe')return ans({status:'ok'});}
state.unknown.push(m+' '+p);return ans({error:{message:'unexpected'}},404)});return {state,page,c};}
try{let {state,page,c}=await fixture();await page.goto(base+'/tenant/providers');await page.getByText('Account A',{exact:true}).waitFor();await page.getByRole('button',{name:'Edit',exact:true}).click();let d=page.getByRole('dialog');assert.equal(await d.locator('select').nth(1).inputValue(),'responses');assert.equal(await d.getByRole('checkbox').isDisabled(),true);await d.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Test',exact:true}).click();await page.getByRole('button',{name:'Passthrough bindings',exact:true}).click();await page.getByText('rev 1',{exact:true}).waitFor();await page.getByRole('button',{name:'Edit',exact:true}).click();d=page.getByRole('dialog');await d.getByRole('checkbox').check();await d.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('rev 2',{exact:true}).waitFor();assert.deepEqual(state.unknown,[]);assert.equal(state.calls.some(x=>x.body?.is_global!==undefined||x.body?.tenant_id!==undefined),false);cases.push('tenant-only account and revision-bound passthrough controls');await c.close();
({state,page,c}=await fixture({admin:false}));await page.goto(base+'/tenant/providers');await page.getByText('Current tenant administrator capability is required.',{exact:true}).waitFor();assert.equal(state.calls.some(x=>x.path.includes('/accounts')||x.path.includes('/passthrough-bindings')),false);await c.close();
({state,page,c}=await fixture());state.hold=true;await page.goto(base+'/tenant/providers');for(let i=0;i<200&&!state.release;i++)await page.waitForTimeout(10);assert.ok(state.release);await page.evaluate(()=>{history.pushState(null,'','/tenant');window.dispatchEvent(new PopStateEvent('popstate'))});await page.locator('#workspace-select').waitFor();await page.locator('#workspace-select').selectOption(B);await page.getByRole('button',{name:'Switch workspace',exact:true}).click();state.release();await page.waitForTimeout(150);assert.doesNotMatch(await page.locator('body').innerText(),/Account A/);cases.push('late provider read cannot publish after workspace switch');await c.close();
assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'report.json'),JSON.stringify({passed:true,basis:'compiled WASM with synthetic HTTP',cases},null,2));console.log(JSON.stringify({passed:true,cases},null,2));}finally{await browser.close();await new Promise(r=>server.close(r));}
