// Production-compiled WASM; synthetic same-origin control API only. No real money movement or payout occurs.
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.KC_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(process.env.KC_WEB_ROOT||'target/dx/web/release/web/public');
const output=path.resolve(process.env.KC_BROWSER_OUTPUT||'tenant-financial-controls-browser-results');await fs.mkdir(output,{recursive:true});
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',U='33333333-3333-4333-8333-333333333333',V='44444444-4444-4444-8444-444444444444';
const R1='55555555-5555-4555-8555-555555555555',R2='66666666-6666-4666-8666-666666666666',RV1='77777777-7777-4777-8777-777777777777',RV2='88888888-8888-4888-8888-888888888888',W='99999999-9999-4999-8999-999999999999';
const stamp='2026-10-01T00:00:00Z';
const server=http.createServer(async(req,res)=>{try{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(file!==root&&!file.startsWith(root+path.sep))throw Error('invalid asset');let data;try{data=await fs.readFile(file);}catch{file=path.join(root,'index.html');data=await fs.readFile(file);}const types={'.html':'text/html','.js':'text/javascript','.wasm':'application/wasm','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);}catch{res.writeHead(500);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let currentPage;const pageErrors=[],cases=[];
const withdrawal=(tenant=A,status='pending',revision=1)=>({id:W,tenant_id:tenant,owner_user_id:V,request_id:R1,withdrawal_type:'alipay',total_amount:'99.0000000001',currency:'CNY',status,payout_details_present:true,admin_id:status==='pending'?null:U,admin_remark:status==='pending'?null:'tenant approval',payout_reference:null,balance_transaction_id:null,revision,actioned_at:status==='pending'?null:stamp,completed_at:null,created_at:stamp,updated_at:stamp});
async function fixture({selected=A,role='none',admin=true}={}){
 const state={selected,role,admin,calls:[],unknown:[],unavailable:false,foreign:false,hold:false,release:null,reservations:[{request_id:R1,version:RV1,amount:'2.0000000001',status:'active',expires_at:'2020-01-01T00:00:00Z',created_at:stamp,updated_at:stamp},{request_id:R2,version:RV2,amount:'3',status:'active',expires_at:'2035-01-01T00:00:00Z',created_at:stamp,updated_at:stamp}],withdrawals:[withdrawal()]};
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>{localStorage.setItem('keyc_access_token','fixture-token');localStorage.setItem('keyc_lang','en');});
 const page=await context.newPage();page.setDefaultTimeout(20000);currentPage=page;page.on('pageerror',e=>pageErrors.push(e.message));
 const profile=()=>({id:U,user_id:U,email:'finance-control@fixture.invalid',name:'Finance control reviewer',platform_role:state.role,status:'active',created_at:stamp,selected_tenant:state.selected?{id:state.selected,name:state.selected===A?'Tenant A':'Tenant B',slug:'fixture',tenant_role:state.selected===A&&state.admin?'admin':'member',authz_version:1,membership_authz_version:1}:null,memberships:[{tenant_id:A,tenant_name:'Tenant A',tenant_role:state.admin?'admin':'member',status:'active',authz_version:1},{tenant_id:B,tenant_name:'Tenant B',tenant_role:'member',status:'active',authz_version:1}],capabilities:{platform:state.role==='root'?['users:manage']:state.role==='operator'?['platform:tenant_health']:[],tenant:state.selected===A&&state.admin?['tenant:manage']:[]}});
 await page.route('**/*',async route=>{
  const req=route.request(),url=new URL(req.url());if(url.origin!==base)return route.abort();if(!url.pathname.startsWith('/api/'))return route.continue();const p=url.pathname,m=req.method(),body=req.postDataJSON();state.calls.push({path:p,method:m,query:url.search,body});
  const answer=(v,status=200)=>route.fulfill({status,contentType:'application/json',headers:{'Cache-Control':'private, no-store','Pragma':'no-cache'},body:JSON.stringify(v)});
  if(p==='/api/v1/settings/public')return answer({site_name:'KeyCompute',distribution_enabled:false});
  if(p==='/api/v1/me'&&m==='GET')return answer(profile());
  if(p==='/api/v1/me/tenant'){state.selected=body.tenant_id;return answer({...profile(),access_token:'fixture-selected',token_type:'Bearer',expires_in:3600});}
  if(p===`/api/v1/tenants/${state.selected}`&&m==='GET')return answer({id:state.selected,owner_user_id:U,name:state.selected===A?'Tenant A':'Tenant B',slug:'fixture',description:null,status:'active',default_rpm_limit:60,default_tpm_limit:100000,authz_version:1,tenant_role:state.selected===A&&state.admin?'admin':'member',membership_authz_version:1});
  const reservationBase=`/api/v1/tenants/${A}/users/${V}/balance/reservations`;
  if(p===reservationBase&&m==='GET'){assert.equal(url.searchParams.get('limit'),'20');assert.equal(url.searchParams.has('tenant_id'),false);return answer({user_id:state.foreign?U:V,available_balance:'7.0000000001',total_frozen_balance:'5.0000000001',request_reserved_balance:'5.0000000001',manually_frozen_balance:'0',reservations:state.reservations,next_cursor:null});}
  if(p===`${reservationBase}/${R1}/release`&&m==='POST'){
   if(state.unavailable)return answer({error:{message:'uncertain recovery'}},503);if(state.hold)await new Promise(resolve=>state.release=resolve);assert.deepEqual(body,{expected_version:RV1,reason:'expired request recovery'});state.reservations=state.reservations.filter(r=>r.request_id!==R1);return answer({success:true,message:'released',user_id:V,request_id:R1,released_amount:'2.0000000001',reason:'expired request recovery',new_available_balance:'9.0000000002',new_total_frozen_balance:'3',request_reserved_balance:'3',manually_frozen_balance:'0',released_by:U,warning:'Late usage may still debit the wallet'});
  }
  const withdrawBase=`/api/v1/tenants/${A}/tips/withdrawals`;
  if(p===withdrawBase&&m==='GET'){assert.equal(url.searchParams.get('currency'),'CNY');assert.equal(url.searchParams.has('tenant_id'),false);let rows=state.withdrawals.map(r=>state.foreign?{...r,tenant_id:B}:r);return answer({items:rows,total:rows.length});}
  if(p===`${withdrawBase}/${W}/approve`&&m==='POST'){
   if(state.unavailable)return answer({error:{message:'uncertain review'}},503);if(state.hold)await new Promise(resolve=>state.release=resolve);assert.deepEqual(body,{expected_revision:1,reason:'tenant approval'});state.withdrawals=[withdrawal(A,'approved',2)];return answer(state.withdrawals[0]);
  }
  if(p===`${withdrawBase}/${W}/reject`&&m==='POST'){assert.deepEqual(body,{expected_revision:1,reason:'tenant rejection'});state.withdrawals=[{...withdrawal(A,'rejected',2),admin_remark:'tenant rejection'}];return answer(state.withdrawals[0]);}
  state.unknown.push(`${m} ${p}`);return answer({error:{message:'unexpected fixture endpoint'}},404);
 });return {state,page,context};
}
async function switchWorkspace(page){await page.evaluate(()=>{history.pushState(null,'','/tenant');window.dispatchEvent(new PopStateEvent('popstate'));});await page.locator('#workspace-select').waitFor();await page.locator('#workspace-select').selectOption(B);await page.getByRole('button',{name:'Switch workspace',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#tenant-name')?.value==='Tenant B');}
async function confirm(d){await d.getByRole('button',{name:'Confirm',exact:true}).click();}
try{
 let {state,page,context}=await fixture();await page.goto(base+'/tenant/finance/controls');await page.getByText('Select a member UUID to inspect that member\'s active request reservations.',{exact:true}).waitFor();await page.locator('#financial-owner').fill(V);await page.getByRole('button',{name:'Load',exact:true}).click();let expiredRow=page.locator('tbody tr').filter({hasText:R1}),activeRow=page.locator('tbody tr').filter({hasText:R2});await expiredRow.waitFor();assert.equal(await expiredRow.getByRole('button',{name:'Recover expired reservation',exact:true}).isDisabled(),false);assert.equal(await activeRow.getByRole('button',{name:'Recover expired reservation',exact:true}).isDisabled(),true);
 await expiredRow.getByRole('button',{name:'Recover expired reservation',exact:true}).click();let d=page.getByRole('dialog');await d.waitFor();await d.locator('#financial-recovery-reason').fill('expired request recovery');await confirm(d);await d.waitFor({state:'detached'});assert.equal(state.calls.filter(c=>c.path.endsWith('/release')&&c.method==='POST').length,1);assert.equal(state.calls.some(c=>c.path.includes('/platform/')||c.path.includes('/support-detail')||c.path.includes('/complete')),false);
 await page.getByRole('button',{name:'Withdrawal review',exact:true}).click();let pending=page.locator('tbody tr').filter({hasText:W});await pending.waitFor();assert.doesNotMatch(await page.locator('body').innerText(),/secret-payee|Private Payee|encrypted_|payout_reference/);await pending.getByRole('button',{name:'Approve',exact:true}).click();d=page.getByRole('dialog');await d.locator('#financial-review-reason').fill('tenant approval');await confirm(d);await d.waitFor({state:'detached'});assert.equal(state.withdrawals[0].status,'approved');assert.equal(state.calls.filter(c=>c.path.endsWith('/approve')).length,1);assert.equal(state.calls.some(c=>c.path.includes('/platform/')||c.path.includes('/support-detail')||c.path.includes('/complete')),false);assert.deepEqual(state.unknown,[]);await page.screenshot({path:path.join(output,'financial-controls.png'),fullPage:true});cases.push('expired-only exact-version recovery and revision-bound metadata-only withdrawal approval without platform payout APIs');await context.close();
 ({state,page,context}=await fixture());await page.goto(base+'/tenant/finance/controls');await page.getByRole('button',{name:'Withdrawal review',exact:true}).click();pending=page.locator('tbody tr').filter({hasText:W});await pending.waitFor();await pending.getByRole('button',{name:'Reject',exact:true}).click();d=page.getByRole('dialog');await d.locator('#financial-review-reason').fill('tenant rejection');await confirm(d);await d.waitFor({state:'detached'});assert.equal(state.withdrawals[0].status,'rejected');assert.equal(state.calls.filter(c=>c.path.endsWith('/reject')).length,1);assert.equal(state.calls.some(c=>c.path.includes('/complete')||c.path.includes('/support-detail')),false);assert.deepEqual(state.unknown,[]);cases.push('explicit rejection uses the observed revision and never enters platform payout completion');await context.close();
 ({state,page,context}=await fixture());state.unavailable=true;await page.goto(base+'/tenant/finance/controls');await page.locator('#financial-owner').fill(V);await page.getByRole('button',{name:'Load',exact:true}).click();expiredRow=page.locator('tbody tr').filter({hasText:R1});await expiredRow.waitFor();await expiredRow.getByRole('button',{name:'Recover expired reservation',exact:true}).click();d=page.getByRole('dialog');await d.locator('#financial-recovery-reason').fill('expired request recovery');await confirm(d);await page.locator('.tenant-reservation-control > [role="alert"]').waitFor();const recoveryCalls=state.calls.filter(c=>c.path.endsWith('/release')).length;await page.waitForTimeout(150);assert.equal(state.calls.filter(c=>c.path.endsWith('/release')).length,recoveryCalls);await d.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Withdrawal review',exact:true}).click();pending=page.locator('tbody tr').filter({hasText:W});await pending.waitFor();await pending.getByRole('button',{name:'Approve',exact:true}).click();d=page.getByRole('dialog');await d.locator('#financial-review-reason').fill('tenant approval');await confirm(d);await page.locator('.tenant-withdrawal-control > [role="alert"]').waitFor();const reviewCalls=state.calls.filter(c=>c.path.endsWith('/approve')).length;await page.waitForTimeout(150);assert.equal(state.calls.filter(c=>c.path.endsWith('/approve')).length,reviewCalls);cases.push('uncertain financial writes are single-dispatch with no automatic retry');await context.close();
 ({state,page,context}=await fixture());state.hold=true;await page.goto(base+'/tenant/finance/controls');await page.getByRole('button',{name:'Withdrawal review',exact:true}).click();pending=page.locator('tbody tr').filter({hasText:W});await pending.waitFor();await pending.getByRole('button',{name:'Approve',exact:true}).click();d=page.getByRole('dialog');await d.locator('#financial-review-reason').fill('tenant approval');await confirm(d);for(let i=0;i<200&&!state.release;i++)await page.waitForTimeout(10);assert.ok(state.release);await switchWorkspace(page);state.release();await page.waitForTimeout(150);assert.doesNotMatch(await page.locator('body').innerText(),/approved · r2|99\.0000000001/);assert.equal(state.calls.filter(c=>c.path.endsWith('/approve')).length,1);await page.goto(base+'/tenant/finance/controls');await page.getByText('Current tenant administrator capability is required.',{exact:true}).waitFor();cases.push('late tenant-A financial result cannot publish or replay in workspace B');await context.close();
 for(const config of [{selected:null,role:'root'},{selected:null,role:'operator'},{admin:false}]){({state,page,context}=await fixture(config));await page.goto(base+'/tenant/finance/controls');await page.getByText(config.selected===null?'This session has no tenant workspace selected. Choose a workspace before viewing tenant data.':'Current tenant administrator capability is required.',{exact:true}).waitFor();assert.equal(state.calls.filter(c=>c.path.includes('/balance/reservations')||c.path.includes('/tips/withdrawals')).length,0);await context.close();}
 ({state,page,context}=await fixture());state.foreign=true;await page.goto(base+'/tenant/finance/controls');await page.locator('#financial-owner').fill(V);await page.getByRole('button',{name:'Load',exact:true}).click();await page.locator('.tenant-reservation-control > [role="alert"]').waitFor();assert.equal(await page.getByRole('button',{name:'Recover expired reservation',exact:true}).count(),0);await page.getByRole('button',{name:'Withdrawal review',exact:true}).click();await page.locator('.tenant-withdrawal-control > [role="alert"]').waitFor();assert.equal(await page.getByRole('button',{name:'Approve',exact:true}).count(),0);assert.deepEqual(state.unknown,[]);cases.push('global roles do not synthesize tenant grants and foreign financial rows fail closed');await context.close();
 assert.deepEqual(pageErrors,[]);const report={passed:true,basis:'production-compiled WASM with synthetic HTTP only; no real money movement or payout authority claim',cases,page_errors:pageErrors};await fs.writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){if(currentPage&&!currentPage.isClosed()){console.error((await currentPage.locator('body').innerText()).slice(0,9000));await currentPage.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});}console.error(error);process.exitCode=1;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
