// Production-compiled WASM; synthetic same-origin control API only. No real settlement/payment occurs.
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.KC_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(process.env.KC_WEB_ROOT||'target/dx/web/release/web/public');
const output=path.resolve(process.env.KC_BROWSER_OUTPUT||'tenant-distribution-browser-results');await fs.mkdir(output,{recursive:true});
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',U='33333333-3333-4333-8333-333333333333',V='44444444-4444-4444-8444-444444444444',R='55555555-5555-4555-8555-555555555555';
const stamp='2026-09-30T00:00:00.123456Z';
const server=http.createServer(async(req,res)=>{try{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(file!==root&&!file.startsWith(root+path.sep))throw Error('invalid asset');let data;try{data=await fs.readFile(file);}catch{file=path.join(root,'index.html');data=await fs.readFile(file);}const types={'.html':'text/html','.js':'text/javascript','.wasm':'application/wasm','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);}catch{res.writeHead(500);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let currentPage;const errors=[],cases=[];
const policy=(tenant=A,id=R)=>({id,tenant_id:tenant,beneficiary_scope:'everyone',beneficiary_id:null,name:'Default future allocation',description:'future only',commission_rate:'0.1250',priority:1,is_active:true,effective_from:'2026-09-01T00:00:00Z',effective_until:'2026-12-01T00:00:00Z',created_at:'2026-09-01T00:00:00Z',updated_at:stamp});
async function fixture({selected=A,role='none',admin=true}={}){
 const state={selected,role,admin,rows:[policy()],calls:[],unknown:[],conflict:false,unavailable:false,hold:false,release:null,foreign:false,next:0};
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>{localStorage.setItem('keyc_access_token','fixture-token');localStorage.setItem('keyc_lang','en');});
 const page=await context.newPage();page.setDefaultTimeout(20000);currentPage=page;page.on('pageerror',e=>errors.push(e.message));
 const profile=()=>({id:U,user_id:U,email:'distribution@fixture.invalid',name:'Distribution reviewer',platform_role:state.role,status:'active',created_at:stamp,selected_tenant:state.selected?{id:state.selected,name:state.selected===A?'Tenant A':'Tenant B',slug:'fixture',tenant_role:state.selected===A&&state.admin?'admin':'member',authz_version:1,membership_authz_version:1}:null,memberships:[{tenant_id:A,tenant_name:'Tenant A',tenant_role:state.admin?'admin':'member',status:'active',authz_version:1},{tenant_id:B,tenant_name:'Tenant B',tenant_role:'member',status:'active',authz_version:1}],capabilities:{platform:state.role==='root'?['users:manage']:state.role==='operator'?['platform:tenant_health']:[],tenant:state.selected===A&&state.admin?['tenant:manage']:[]}});
 await page.route('**/*',async route=>{
  const req=route.request(),url=new URL(req.url());if(url.origin!==base)return route.abort();if(!url.pathname.startsWith('/api/'))return route.continue();const p=url.pathname,m=req.method(),body=req.postDataJSON();state.calls.push({path:p,method:m,query:url.search,body});
  const answer=(v,status=200)=>route.fulfill({status,contentType:'application/json',headers:{'Cache-Control':'private, no-store'},body:JSON.stringify(v)});
  if(p==='/api/v1/settings/public')return answer({site_name:'KeyCompute',distribution_enabled:true});
  if(p==='/api/v1/me'&&m==='GET')return answer(profile());
  if(p==='/api/v1/me/tenant'){state.selected=body.tenant_id;return answer({...profile(),access_token:'fixture-selected',token_type:'Bearer',expires_in:3600});}
  if(p===`/api/v1/tenants/${state.selected}`&&m==='GET')return answer({id:state.selected,owner_user_id:U,name:state.selected===A?'Tenant A':'Tenant B',slug:'fixture',description:null,status:'active',default_rpm_limit:60,default_tpm_limit:100000,authz_version:1,tenant_role:state.selected===A&&state.admin?'admin':'member',membership_authz_version:1});
  if(p===`/api/v1/tenants/${A}/members`&&m==='GET')return answer({items:[{user_id:U,email:'admin@fixture.invalid',name:'Admin',user_status:'active',tenant_role:'admin',membership_status:'active',authz_version:1,invited_by:null,joined_at:stamp,removed_at:null},{user_id:V,email:'member@fixture.invalid',name:'Member',user_status:'active',tenant_role:'member',membership_status:'active',authz_version:1,invited_by:null,joined_at:stamp,removed_at:null}],total:2,page:1,page_size:100,total_pages:1});
  const root=`/api/v1/tenants/${A}/distribution/rules`;
  if(p===root&&m==='GET'){let rows=state.foreign?state.rows.map(r=>({...r,tenant_id:B})):state.rows;const n=Number(url.searchParams.get('page')||1),size=Number(url.searchParams.get('page_size')||20);return answer({rules:rows.slice((n-1)*size,n*size),total:rows.length,page:n,page_size:size,total_pages:Math.ceil(rows.length/size)});}
  if(p===`${root}/default`&&m==='POST'){if(state.unavailable)return answer({error:{message:'uncertain default'}},503);assert.equal(body.tenant_id,undefined);assert.equal(body.beneficiary_id,undefined);const r={...policy(),id:'66666666-6666-4666-8666-666666666666',name:body.name,commission_rate:body.commission_rate,priority:100,updated_at:`2026-09-30T00:00:0${++state.next}Z`};state.rows.push(r);return answer(r);}
  if(p===root&&m==='POST'){if(state.unavailable)return answer({error:{message:'uncertain create'}},503);assert.equal(body.tenant_id,undefined);const id='77777777-7777-4777-8777-777777777777';const r={...policy(),...body,id,tenant_id:A,is_active:true,effective_from:body.effective_from??stamp,created_at:stamp,updated_at:`2026-09-30T00:00:0${++state.next}Z`};delete r.reason;state.rows.push(r);return answer(r);}
  if(p===`${root}/${R}`&&m==='PATCH'){if(state.conflict)return answer({error:{message:'Policy or authorization changed; reload and retry'}},409);if(state.unavailable)return answer({error:{message:'uncertain patch'}},503);if(state.hold)await new Promise(resolve=>state.release=resolve);const row=state.rows.find(r=>r.id===R);assert.equal(body.expected_updated_at,row.updated_at);assert.equal(body.tenant_id,undefined);for(const [k,v] of Object.entries(body)){if(!['expected_updated_at','reason'].includes(k))row[k]=v;}row.updated_at=`2026-09-30T00:00:0${++state.next}Z`;return answer(row);}
  if(p===`${root}/${R}`&&m==='DELETE'){if(state.unavailable)return answer({error:{message:'uncertain delete'}},503);const row=state.rows.find(r=>r.id===R);assert.equal(body.expected_updated_at,row.updated_at);state.rows=state.rows.filter(r=>r.id!==R);return answer({id:R,deleted:true});}
  state.unknown.push(`${m} ${p}`);return answer({error:{message:'unexpected fixture endpoint'}},404);
 });return {state,page,context};
}
async function dialog(page){const d=page.getByRole('dialog');await d.waitFor();return d;}
async function confirm(d){await d.getByRole('button',{name:'Confirm',exact:true}).click();}
try{
 let {state,page,context}=await fixture();await page.goto(base+'/tenant/distribution');await page.getByText('Default future allocation',{exact:true}).waitFor();assert.match(await page.locator('tbody').innerText(),/0\.1250/);
 await page.locator('tbody tr').filter({hasText:'Default future allocation'}).getByRole('button',{name:'Edit',exact:true}).click();let d=await dialog(page);assert.match(await d.innerText(),new RegExp(R));assert.equal(await d.locator('#distribution-from').isDisabled(),true);await d.locator('#distribution-rate').fill('0.2500');await d.locator('#distribution-description').fill('');await d.locator('#distribution-until').fill('');await d.locator('#distribution-reason').fill('adjust future allocation');await confirm(d);await d.waitFor({state:'detached'});let patch=state.calls.find(c=>c.method==='PATCH');assert.equal(patch.body.expected_updated_at,stamp);assert.equal(patch.body.commission_rate,'0.2500');assert.equal(patch.body.description,null);assert.equal(patch.body.effective_until,null);assert.equal(patch.body.beneficiary_id,undefined);
 await page.locator('tbody tr').filter({hasText:'Default future allocation'}).getByRole('button',{name:'Edit',exact:true}).click();d=await dialog(page);await d.locator('#distribution-rate').fill('0.12345');await d.locator('#distribution-reason').fill('invalid');const before=state.calls.filter(c=>c.method==='PATCH').length;await confirm(d);await d.locator('[role="alert"]').waitFor();assert.equal(state.calls.filter(c=>c.method==='PATCH').length,before);await d.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Create policy',exact:true}).click();d=await dialog(page);await d.locator('#distribution-name').fill('Member future allocation');await d.locator('#distribution-rate').fill('0.3333');await d.locator('#distribution-beneficiary').selectOption('tenant_member');await d.locator('#distribution-member').fill(V);await d.locator('#distribution-priority').fill('7');await d.locator('#distribution-reason').fill('member-specific future allocation');await confirm(d);await d.waitFor({state:'detached'});await page.getByText('Member future allocation',{exact:true}).waitFor();const created=state.calls.filter(c=>c.method==='POST'&&c.path===`/api/v1/tenants/${A}/distribution/rules`).at(-1);assert.equal(created.body.beneficiary_scope,'tenant_member');assert.equal(created.body.beneficiary_id,V);assert.equal(created.body.tenant_id,undefined);
 await page.getByRole('button',{name:'Set tenant default',exact:true}).click();d=await dialog(page);await d.locator('#distribution-name').fill('Tenant default');await d.locator('#distribution-rate').fill('0.1000');await d.locator('#distribution-reason').fill('set future default');await confirm(d);await d.waitFor({state:'detached'});const def=state.calls.find(c=>c.path.endsWith('/rules/default'));assert.deepEqual(def.body,{name:'Tenant default',commission_rate:'0.1000',reason:'set future default'});
 const expectedDeleteRevision=state.rows.find(r=>r.id===R).updated_at;await page.locator('tbody tr').filter({hasText:'Default future allocation'}).getByRole('button',{name:'Delete',exact:true}).click();d=await dialog(page);await d.locator('#distribution-reason').fill('obsolete future policy');await confirm(d);await d.waitFor({state:'detached'});const del=state.calls.find(c=>c.method==='DELETE');assert.equal(del.body.expected_updated_at,expectedDeleteRevision);assert.equal(del.body.reason,'obsolete future policy');assert.equal(state.rows.some(r=>r.id===R),false);
 assert.equal(state.calls.some(c=>/payments|settlement|withdraw/.test(c.path)),false);assert.deepEqual(state.unknown,[]);await page.screenshot({path:path.join(output,'distribution.png'),fullPage:true});cases.push('exact rates and revisions, immutable beneficiary, member create/default/delete and no settlement endpoint');await context.close();
 ({state,page,context}=await fixture());state.unavailable=true;await page.goto(base+'/tenant/distribution');await page.getByText('Default future allocation',{exact:true}).waitFor();await page.getByRole('button',{name:'Set tenant default',exact:true}).click();d=await dialog(page);await d.locator('#distribution-name').fill('Uncertain');await d.locator('#distribution-rate').fill('0.1');await d.locator('#distribution-reason').fill('uncertain command');await confirm(d);await d.locator('[role="alert"]').waitFor();assert.equal(state.calls.filter(c=>c.path.endsWith('/rules/default')).length,1);await page.waitForTimeout(150);assert.equal(state.calls.filter(c=>c.path.endsWith('/rules/default')).length,1);cases.push('uncertain policy write is single-dispatch');await context.close();
 ({state,page,context}=await fixture());state.hold=true;await page.goto(base+'/tenant/distribution');await page.getByText('Default future allocation',{exact:true}).waitFor();await page.locator('tbody').getByRole('button',{name:'Edit',exact:true}).click();d=await dialog(page);await d.locator('#distribution-rate').fill('0.7777');await d.locator('#distribution-reason').fill('delayed');await confirm(d);for(let i=0;i<200&&!state.release;i++)await page.waitForTimeout(10);assert.ok(state.release);await page.evaluate(()=>{history.pushState(null,'','/tenant');window.dispatchEvent(new PopStateEvent('popstate'));});await page.locator('#workspace-select').waitFor();await page.locator('#workspace-select').selectOption(B);await page.getByRole('button',{name:'Switch workspace',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#tenant-name')?.value==='Tenant B');state.release();await page.waitForTimeout(150);assert.doesNotMatch(await page.locator('body').innerText(),/0\.7777|Changes saved/);assert.equal(state.calls.filter(c=>c.method==='PATCH').length,1);await page.goto(base+'/tenant/distribution');await page.getByText('Current tenant administrator capability is required.',{exact:true}).waitFor();cases.push('late tenant A policy write cannot publish or replay in member workspace B');await context.close();
 for(const role of ['root','operator']){({state,page,context}=await fixture({selected:null,role}));await page.goto(base+'/tenant/distribution');await page.getByText('Current tenant administrator capability is required.',{exact:true}).waitFor();assert.equal(state.calls.filter(c=>c.path.includes('/distribution/rules')).length,0);await context.close();}
 ({state,page,context}=await fixture());state.foreign=true;await page.goto(base+'/tenant/distribution');await page.locator('.tenant-distribution-admin [role="alert"]').waitFor();assert.equal(await page.getByRole('button',{name:'Edit',exact:true}).count(),0);cases.push('global roles do not synthesize tenant grant; foreign policy rows fail closed');await context.close();
 assert.deepEqual(errors,[]);const report={passed:true,basis:'production-compiled WASM with synthetic HTTP only; no production settlement/payment claim',cases,page_errors:errors};await fs.writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){if(currentPage&&!currentPage.isClosed()){console.error((await currentPage.locator('body').innerText()).slice(0,8000));await currentPage.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});}console.error(error);process.exitCode=1;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
